title: Jekyll Serial Programmer
markdown: kramdown

# for atom feed
author:
  name: Sharad Raj Singh Maurya
  email: dev_sharad@outlook.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

domain: irfanalmsyah.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://irfanalmsyah.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/jekyll-test/" # the subpath of your site, e.g. /blog

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
